version: '3.8'

services:
  backend:
    env_file:
      - .env
    image: jathurt/myapp-backend:latest
    container_name: dental-backend
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - dental-network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: dental-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - MYSQL_DATABASE=dental
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dental-network
    restart: always

#  prometheus:
#    image: prom/prometheus:latest
#    container_name: dental-prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus-data:/prometheus
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
#      - '--web.console.templates=/usr/share/prometheus/consoles'
#    networks:
#      - dental-network
#    restart: always
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: dental-grafana
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
#      - GF_USERS_ALLOW_SIGN_UP=false
#    volumes:
#      - grafana-data:/var/lib/grafana
#    depends_on:
#      - prometheus
#    networks:
#      - dental-network
#    restart: always

networks:
  dental-network:
    driver: bridge

volumes:
  mysql-data:
#  prometheus-data:
#  grafana-data: