#global:
#  scrape_interval: 15s
#  evaluation_interval: 15s
#
#scrape_configs:
#  - job_name: 'dental-backend'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['backend:8081']
#
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['prometheus:9090']